dsun-T14-g3:
    usecase: "personal"
    offworld_setup: False
    ROS_distros: ["humble"]

dsun-T15p-g3:
    usecase: "business"
    offworld_setup: True
    ROS_distros: ["noetic", "galactic"]

default:
    usecase: "business"
    offworld_setup: False

