dsun-T14-g3:
    usecase: "personal"
    offworld_setup: False
    ROS_distros: ["humble"]
    environment_variables:
    - DS_PROFILE_CONFIG: True


OWUS-DSUN-UL:
    usecase: "business"
    offworld_setup: True
    ROS_distros: ["noetic", "galactic"]
    environment_variables:
    - DS_PROFILE_CONFIG: True

default:
    usecase: "personal"
    offworld_setup: False
    environment_variables:
    - DS_PROFILE_CONFIG: True

